package com.pininicong.cashbook.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/** 저축 잔액: anchor/adjustment/period_summary 테이블 및 관련 컬럼 보강. */
@Component
@Order(12)
public class SavingsBalanceSchemaMigrationRunner implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(SavingsBalanceSchemaMigrationRunner.class);

    private final JdbcTemplate jdbc;

    public SavingsBalanceSchemaMigrationRunner(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public void run(ApplicationArguments args) {
        ensureTransactionColumn("savings_product_id", "bigint");
        ensureProductColumns();
        ensureAnchorTable();
        ensureAdjustmentTable();
        ensurePeriodSummaryTable();
    }

    private void ensureTransactionColumn(String column, String type) {
        if (!tableExists("cb_transaction")) {
            return;
        }
        addColumnIfMissing("cb_transaction", column, type);
    }

    private void ensureProductColumns() {
        if (!tableExists("cb_financial_product")) {
            return;
        }
        addColumnIfMissing("cb_financial_product", "opening_balance", "decimal(19,2)");
        addColumnIfMissing("cb_financial_product", "opening_date", "date");
        try {
            jdbc.update(
                    """
                    UPDATE cb_financial_product
                    SET opening_balance = 0
                    WHERE opening_balance IS NULL
                    """);
        } catch (Exception e) {
            log.warn("opening_balance backfill skipped: {}", e.getMessage());
        }
    }

    private void ensureAnchorTable() {
        if (tableExists("cb_product_balance_anchor")) {
            return;
        }
        try {
            jdbc.execute(
                    """
                    CREATE TABLE cb_product_balance_anchor (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      book VARCHAR(16) NOT NULL,
                      product_id BIGINT NOT NULL,
                      anchor_date DATE NOT NULL,
                      balance DECIMAL(19,2) NOT NULL,
                      remarks VARCHAR(500)
                    )
                    """);
            log.info("cb_product_balance_anchor 테이블 생성");
        } catch (Exception e) {
            log.warn("cb_product_balance_anchor ensure skipped: {}", e.getMessage());
        }
    }

    private void ensureAdjustmentTable() {
        if (tableExists("cb_balance_adjustment")) {
            return;
        }
        try {
            jdbc.execute(
                    """
                    CREATE TABLE cb_balance_adjustment (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      book VARCHAR(16) NOT NULL,
                      product_id BIGINT NOT NULL,
                      adj_date DATE NOT NULL,
                      amount DECIMAL(19,2) NOT NULL,
                      reason VARCHAR(200)
                    )
                    """);
            log.info("cb_balance_adjustment 테이블 생성");
        } catch (Exception e) {
            log.warn("cb_balance_adjustment ensure skipped: {}", e.getMessage());
        }
    }

    private void ensurePeriodSummaryTable() {
        if (tableExists("cb_product_period_summary")) {
            return;
        }
        try {
            jdbc.execute(
                    """
                    CREATE TABLE cb_product_period_summary (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      book VARCHAR(16) NOT NULL,
                      product_id BIGINT NOT NULL,
                      period_type VARCHAR(8) NOT NULL,
                      period_key VARCHAR(16) NOT NULL,
                      inflow DECIMAL(19,2) NOT NULL,
                      outflow DECIMAL(19,2) NOT NULL,
                      net_flow DECIMAL(19,2) NOT NULL,
                      end_balance DECIMAL(19,2) NOT NULL
                    )
                    """);
            log.info("cb_product_period_summary 테이블 생성");
        } catch (Exception e) {
            log.warn("cb_product_period_summary ensure skipped: {}", e.getMessage());
        }
    }

    private void addColumnIfMissing(String table, String column, String type) {
        if (!tableExists(table) || columnExists(table, column)) {
            return;
        }
        try {
            jdbc.execute("ALTER TABLE " + table + " ADD COLUMN " + column + " " + type);
            log.info("{} column added: {}", table, column);
        } catch (Exception e) {
            log.warn("{} column ensure skipped ({}): {}", table, column, e.getMessage());
        }
    }

    private boolean tableExists(String table) {
        Integer count =
                jdbc.queryForObject(
                        """
                        SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                        WHERE UPPER(TABLE_NAME) = UPPER(?)
                        """,
                        Integer.class,
                        table);
        return count != null && count > 0;
    }

    private boolean columnExists(String table, String column) {
        Integer count =
                jdbc.queryForObject(
                        """
                        SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                        WHERE UPPER(TABLE_NAME) = UPPER(?) AND UPPER(COLUMN_NAME) = UPPER(?)
                        """,
                        Integer.class,
                        table,
                        column);
        return count != null && count > 0;
    }
}
